import request from "../utils/request";

export const adminApi = {
  login: (data) => request.post("/api/admin/login", data),
  getDashboard: () => request.get("/api/admin/dashboard"),
  getGoods: (params) => request.get("/api/admin/goods/list", { params }),
  saveGoods: (data) => request.post(data.id ? "/api/admin/goods/update" : "/api/admin/goods/create", data),
  deleteGoods: (id) => request.post("/api/admin/goods/delete", { id }),
  toggleGoods: (id) => request.post("/api/admin/goods/toggle", { id }),
  getCategories: (params) => request.get("/api/admin/categories/list", { params }),
  saveCategory: (data) => request.post("/api/admin/categories/save", data),
  getBanners: (params) => request.get("/api/admin/banners/list", { params }),
  saveBanner: (data) => request.post("/api/admin/banners/save", data),
  getSections: (params) => request.get("/api/admin/sections/list", { params }),
  saveSection: (data) => request.post("/api/admin/sections/save", data),
  getCoupons: (params) => request.get("/api/admin/coupons/list", { params }),
  saveCoupon: (data) => request.post("/api/admin/coupons/save", data),
  getOrders: (params) => request.get("/api/admin/orders/list", { params }),
  getOrderDetail: (id) => request.get(`/api/admin/orders/${id}`),
  updateOrderStatus: (data) => request.post("/api/admin/orders/update-status", data),
  getUsers: (params) => request.get("/api/admin/users/list", { params }),
  getCommunities: (params) => request.get("/api/admin/communities/list", { params }),
  saveCommunity: (data) => request.post("/api/admin/communities/save", data),
  getContents: (params) => request.get("/api/admin/contents/list", { params }),
  saveContent: (data) => request.post("/api/admin/contents/save", data),
  getServiceTickets: (params) => request.get("/api/admin/service-tickets/list", { params }),
  updateServiceTicket: (data) => request.post("/api/admin/service-tickets/update", data),
  getSystemConfig: () => request.get("/api/admin/system-config"),
  saveSystemConfig: (data) => request.post("/api/admin/system-config/save", data)
};
