// 统一引入 request 函数
const request = require("../utils/request.js");

module.exports = {
  getConfig: () => request({ url: "/api/config" }),
  getCommunities: (params = {}) => request({ url: "/api/communities", data: params }),
  getBanners: (params = {}) => request({ url: "/api/banners", data: params }),
  getSections: (params = {}) => request({ url: "/api/sections", data: params }),
  getCategories: () => request({ url: "/api/categories" }),
  getGoods: (params = {}) => request({ url: "/api/goods", data: params }),
  getGoodsDetail: (id) => request({ url: `/api/goods/${id}` }),
  searchGoods: (params = {}) => request({ url: "/api/search", data: params }),
  login: (data) => request({ url: "/api/auth/login", method: "POST", data }),
  getUserProfile: () => request({ url: "/api/user/profile", auth: true }),
  getFavorites: () => request({ url: "/api/user/favorites", auth: true }),
  toggleFavorite: (data) => request({ url: "/api/user/favorites/toggle", method: "POST", data, auth: true }),
  getHistory: () => request({ url: "/api/user/history", auth: true }),
  addHistory: (data) => request({ url: "/api/user/history/add", method: "POST", data, auth: true }),
  getCart: () => request({ url: "/api/cart", auth: true }),
  addCart: (data) => request({ url: "/api/cart/add", method: "POST", data, auth: true }),
  updateCart: (data) => request({ url: "/api/cart/update", method: "POST", data, auth: true }),
  removeCart: (data) => request({ url: "/api/cart/remove", method: "POST", data, auth: true }),
  clearCart: () => request({ url: "/api/cart/clear", method: "POST", auth: true }),
  getCouponCenter: () => request({ url: "/api/coupons/center", auth: true }),
  claimCoupon: (data) => request({ url: "/api/coupons/claim", method: "POST", data, auth: true }),
  getMyCoupons: () => request({ url: "/api/coupons/my", auth: true }),
  getAddressList: () => request({ url: "/api/address/list", auth: true }),
  saveAddress: (data) => request({ url: "/api/address/save", method: "POST", data, auth: true }),
  deleteAddress: (data) => request({ url: "/api/address/delete", method: "POST", data, auth: true }),
  orderPreview: (data) => request({ url: "/api/order/preview", method: "POST", data, auth: true }),
  orderCreate: (data) => request({ url: "/api/order/create", method: "POST", data, auth: true }),
  orderPay: (data) => request({ url: "/api/order/pay", method: "POST", data, auth: true }),
  getOrderList: (params = {}) => request({ url: "/api/order/list", data: params, auth: true }),
  getOrderDetail: (id) => request({ url: `/api/order/${id}`, auth: true }),
  cancelOrder: (data) => request({ url: "/api/order/cancel", method: "POST", data, auth: true }),
  confirmOrder: (data) => request({ url: "/api/order/confirm", method: "POST", data, auth: true }),
  createServiceTicket: (data) => request({ url: "/api/service-ticket/create", method: "POST", data, auth: true }),
  getServiceTickets: () => request({ url: "/api/service-ticket/list", auth: true }),
  getContentList: (params = {}) => request({ url: "/api/content/list", data: params }),
  getContentDetail: (id) => request({ url: `/api/content/${id}` })
};